# Generated by Django 5.2.13 on 2026-04-25 00:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_generated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_extraction', 'Pending AI'), ('audit_required', 'Needs Audit'), ('verified', 'Verified')], db_index=True, default='pending_extraction', max_length=32)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extraction_error', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=512)),
                ('date_issued', models.DateField(blank=True, db_index=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('ollama_model_used', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_rows', to='documents.category')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='documents.invoicedocument')),
            ],
            options={
                'verbose_name_plural': 'extracted data',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=255)),
                ('original_value_from_ai', models.TextField(blank=True)),
                ('corrected_value_from_user', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.invoicedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('extracted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.extracteddata')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicedocument',
            index=models.Index(fields=['status', '-upload_date'], name='documents_i_status_f57a76_idx'),
        ),
    ]
