# Generated by Django 5.2.13 on 2026-04-25 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('event', models.CharField(blank=True, db_index=True, help_text='Short machine key, e.g. extraction_started, vision_ok.', max_length=64)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='documents.invoicedocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='documents_e_documen_09d03f_idx')],
            },
        ),
    ]
