# Generated by Django 5.2.13 on 2026-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_systemsettings_ollama_ocr_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ollama_ocr_model',
            field=models.CharField(blank=True, default='', help_text='Plain-text OCR from images, e.g. glm-ocr:latest. When set, OCR uses this model instead of the vision model and does not require vision_model_supports_vision. Leave blank to OCR with the vision model.', max_length=256, verbose_name='OCR model (optional)'),
        ),
    ]
