# Generated by Django 5.0.2 on 2026-04-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_airuntimelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='crew_category_model',
            field=models.CharField(blank=True, default='', help_text='Model for Crew category stage (blank = ollama_text_model).', max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='crew_hint_max_chars',
            field=models.PositiveIntegerField(default=1200, help_text='Maximum guidance text length from Crew stages.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='crew_max_retries',
            field=models.PositiveIntegerField(default=2, help_text='Retries per Crew stage when transient errors occur.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='crew_read_model',
            field=models.CharField(blank=True, default='', help_text='Model for Crew read stage (blank = ollama_text_model).', max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='crew_stage_timeout_seconds',
            field=models.PositiveIntegerField(default=45, help_text='Per-stage timeout budget for Crew operations.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='crew_structure_model',
            field=models.CharField(blank=True, default='', help_text='Model for Crew structure stage (blank = ollama_text_model).', max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='crew_validate_model',
            field=models.CharField(blank=True, default='', help_text='Model for Crew validate stage (blank = ollama_text_model).', max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='use_crewai_hints',
            field=models.BooleanField(default=True, help_text='Enable CrewAI stage hints before text structuring.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='auto_start_model_server',
            field=models.BooleanField(default=False, help_text='Legacy setting (unused in Ollama mode).'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='model_server_start_command',
            field=models.TextField(blank=True, default='', help_text='Legacy setting (unused in Ollama mode).'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='model_server_start_timeout_seconds',
            field=models.PositiveIntegerField(default=45, help_text='Legacy setting (unused in Ollama mode).'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='text_model_base_url',
            field=models.CharField(default='http://127.0.0.1:11434', help_text='Legacy per-role endpoint (unused in Ollama single-server mode).', max_length=512),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='text_model_server_start_command',
            field=models.TextField(blank=True, default='', help_text='Legacy setting (unused in Ollama mode).'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vision_model_base_url',
            field=models.CharField(default='http://127.0.0.1:11435', help_text='Legacy per-role endpoint (unused in Ollama single-server mode).', max_length=512),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vision_model_server_start_command',
            field=models.TextField(blank=True, default='', help_text='Legacy setting (unused in Ollama mode).'),
        ),
    ]
