# Generated by Django 5.0.2 on 2026-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_systemsettings_crew_category_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedocument',
            name='extraction_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Total extraction attempts performed for this document.'),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='last_rescan_reason',
            field=models.CharField(blank=True, default='', help_text='Latest reason a rescan/retry was triggered.', max_length=512),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_document_rescan_attempts',
            field=models.PositiveIntegerField(default=2, help_text='Maximum full OCR rescan + re-audit attempts per document.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rescan_backoff_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Delay between automatic rescan attempts in seconds.'),
        ),
    ]
